from src.prompts.templates import (
    CHAIN_OF_THOUGHT_PREAMBLE,
    GENERATION_SYSTEM_PROMPT,
    GENERATION_USER_TEMPLATE,
    HALLUCINATION_CHECK_PROMPT,
)

__all__ = [
    "CHAIN_OF_THOUGHT_PREAMBLE",
    "GENERATION_SYSTEM_PROMPT",
    "GENERATION_USER_TEMPLATE",
    "HALLUCINATION_CHECK_PROMPT",
]
